name: npm build deploy via ftp
on:
  push:
    paths-ignore:  # これらへの変更でプッシュされてもgithub actionsを動かさない
      - ‘.github/**’
      - ‘!.github/workflows/**’
      - ‘docs/**’
      - ‘README.md’
      - ‘.gitignore’
      - ‘.gitmodules’
      
jobs:
  build:
    uses: steamships/.github/.github/workflows/nodejs-build.yml@main

  Commit-output:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: “自動ビルド:${{github.sha}}”
        branch: ${{ steps.extract_branch.outputs.branch }}

  deploy-via-ftp:
    uses: steamships/.github/.github/workflows/ftp-deploy.yml@main
    secrets: inherit
