name: npm build deploy via ftp
on:
  push:
    paths-ignore:  # これらへの変更でプッシュされてもgithub actionsを動かさない
      - ‘.github/**’
      - ‘!.github/workflows/**’
      - ‘docs/**’
      - ‘README.md’
      - ‘.gitignore’
      - ‘.gitmodules’
      
jobs:
  build:
    uses: steamships/.github/.github/workflows/nodejs-build.yml@main

  deploy-via-ftp:
    needs: build
    uses: steamships/.github/.github/workflows/ftp-deploy.yml@main
    secrets: inherit
    with:
      source-path: 
      destination-path: 
