name: node js build(this workflow commits files under dist)
on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        token: ${{ secrets.PAT }}
      env:
        BRANCH: "${GITHUB_REF#refs/heads/}"
        MESSAGE: "Build: ({sha}) {msg}"
    - run: |
        npm ci
        npm run build --if-present
    - uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: “自動ビルド:${{github.sha}}”
        branch: “${GITHUB_REF#refs/heads/}”
